#!/bin/sh
set -e

if ! command -v git &> /dev/null
then
	echo "git should be installed"
	exit 255
fi

git clone https://github.com/ivabus/dotfiles $HOME/.dotfiles
exec sh $HOME/.dotfiles/tools/install.sh < /dev/tty
