window:
  dimensions:
    columns: 80
    lines: 25
  padding:
    x: 5
    y: 5

scrolling:
  history: 100000
  multiplier: 3

font:

  normal:
    family: JetBrains Mono
    style: Regular

  bold:
    family: JetBrains Mono
    style: Bold

  italic:
    family: JetBrains Mono
    style: Italic

  size: 9.0

colors:
  # Default colors
  primary:
    # hard contrast: background = '0x1d2021'
    background: '0x282828'
    # soft contrast: background = '0x32302f'
    foreground: '0xebdbb2'

  # Normal colors
  normal:
    black:   '0x282828'
    red:     '0xcc241d'
    green:   '0x98971a'
    yellow:  '0xd79921'
    blue:    '0x458588'
    magenta: '0xb16286'
    cyan:    '0x689d6a'
    white:   '0xa89984'

  # Bright colors
  bright:
    black:   '0x928374'
    red:     '0xfb4934'
    green:   '0xb8bb26'
    yellow:  '0xfabd2f'
    blue:    '0x83a598'
    magenta: '0xd3869b'
    cyan:    '0x8ec07c'
    white:   '0xebdbb2'

cursor:
  shape: Block
  blinking: on

shell:
  program: /bin/zsh
  args:
    - --login
