window:
  dimensions:
    columns: 80
    lines: 25
  padding:
    x: 5
    y: 5
scrolling:
  history: 100000
  multiplier: 3

font:
  normal:
    family: JetBrains Mono
    style: SemiBold

  bold:
    family: JetBrains Mono
    style: Bold

  italic:
    family: JetBrains Mono
    style: SemiBold Italic
  size: 8.0

cursor:
  shape: Block
  blinking: on


# Colors (Solarized Dark)
colors:
  # Default colors
  primary:
    background: '#002b36' # base03
    foreground: '#839496' # base0

  # Cursor colors
  cursor:
    text:   '#002b36' # base03
    cursor: '#839496' # base0

  # Normal colors
  normal:
    black:   '#073642' # base02
    red:     '#dc322f' # red
    green:   '#859900' # green
    yellow:  '#b58900' # yellow
    blue:    '#268bd2' # blue
    magenta: '#d33682' # magenta
    cyan:    '#2aa198' # cyan
    white:   '#eee8d5' # base2

