export ZSH="$HOME/.dotfiles/oh-my-zsh"

ZSH_THEME="ivabus"

plugins=(git zsh-syntax-highlighting)

alias upgrade_dotfiles="sh $HOME/.dotfiles/tools/upgrade.sh"

source $ZSH/oh-my-zsh.sh

alias vi="nvim"
alias vim="nvim"


alias show_current_keys="wshowkeys -F \"JetBrains Mono 9\" -a left -a bottom -t 1"
