window:
  dimensions:
    columns: 80
    lines: 25
  padding:
    x: 5
    y: 5
  opacity: 1
scrolling:
  history: 100000
  multiplier: 3

font:
  normal:
    family: JetBrains Mono
    style: SemiBold

  bold:
    family: JetBrains Mono
    style: Bold

  italic:
    family: JetBrains Mono
    style: SemiBold Italic
  size: 8.0

cursor:
  shape: Block
  blinking: on

colors:
  primary:
    background: '0x1d2021'
    foreground: '0xd4be98'
  normal:
    black:   '0x32302f'
    red:     '0xea6962'
    green:   '0xa9b665'
    yellow:  '0xd8a657'
    blue:    '0x7daea3'
    magenta: '0xd3869b'
    cyan:    '0x89b482'
    white:   '0xd4be98'
  bright:
    black:   '0x32302f'
    red:     '0xea6962'
    green:   '0xa9b665'
    yellow:  '0xd8a657'
    blue:    '0x7daea3'
    magenta: '0xd3869b'
    cyan:    '0x89b482'
    white:   '0xd4be98'
